=== Hi there 👋

image:https://holopin.me/ronnypolley[link="https://holopin.io/@ronnypolley",alt="@ronnypolley's Holopin board"]

=== Technical Skills 🛠️
[%collapsible]
.Click for more details
====
* **Programming Languages**: Java, Python, JavaScript, TypeScript, SQL
* **Testing**: JUnit, Mockito, Selenium, Spock, Pester
* **Architectural Styles**: Microservices, RESTful APIs, SOAP, Event-Driven Architecture
* **Frameworks & Libraries**: Spring Boot, Quarkus
* **Build Tools**: Maven, Gradle, npm
* **DevOps Tools**: Docker, Kubernetes, Jenkins, GitLab CI/CD
* **Cloud Services**: Azure Kubernetes Service (AKS)
* **Monitoring & Logging**: Prometheus, Grafana, ELK Stack
* **Cloud Platforms**: Azure
* **Databases**: MySQL, PostgreSQL
* **Version Control**: Git, SVN, CVS
* **Other Tools**: Eclipse, IntelliJ IDEA, JIRA, Confluence, (Neo)Vim
* **Security**: DevSecOps practices, secure coding, vulnerability assessment
* **Project Management**: Agile methodologies, Scrum
* **Soft Skills**: Leadership, communication, problem-solving, teamwork
* **Languages**: English (fluent), German (native)
* **Certifications**: Certified Scrum Product Owner (CSPO)
* **Interests**: Software architecture, cloud computing, automotive software solutions, DevSecOps
====

=== Jokes 😂

[.text-center]
image:https://readme-jokes.vercel.app/api?hideBorder[]

=== My Experiences 🙌

[cols="1,2,3", options="header"]
|===
|Period |Position |Company & Activities

|since 2025-06
|*Project Lead*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH]

* Leading a team of 10+ developers delivering custom software solutions for a world leading commercial vehicle manufacturer

|since 2014-06
|*Senior Software Engineer and Product Owner*
a|link:https://www.itsonix.eu/[@IT Sonix custom development GmbH]

* Software development and product ownership for custom software solutions in the automotive industry.
** Old Eclipse RCP application...
** Services and microservices...
** API development...

...for vehicle configuration and order management

* DevSecOps and security engineering for custom software solutions in the automotive industry.

|
|*Team Lead Product Management*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH] DevSecOps Project

* Leading a team of 4 product owners in varying customer and industry segments to deliver a comprehensive DevSecOps product suite.

|2012-06 to 2014-05
|*Senior Software Engineer*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH]

* Software development for custom software solutions in the automotive industry.

|2011-10 to 2012-05
|*Software Engineer*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH]

* Software development for custom software solutions in the automotive industry.

|2010-04 to 2011-09
|*Software Engineer*
a|link:https://www.heise.de/news/Software-AG-uebernimmt-restliche-Anteile-von-itCampus-1012299.html[@itcampus]

* Software development for custom software solutions in the automotive industry.

|===

////
**ronnypolley/ronnypolley** is a ✨ _special_ ✨ repository because its `README.adoc` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 👯 I'm looking to collaborate on ...
- 🤔 I'm looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
////

