=== Hi there 👋

image:https://holopin.me/ronnypolley[link="https://holopin.io/@ronnypolley",alt="@ronnypolley's Holopin board"]

=== My Experiences 🙌

[cols="1,2,3", options="header"]
|===
|Period |Position |Company & Activities

|since 2025-06
|*Project Lead*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH]

* Leading a team of 10+ developers delivering custom software solutions for a world leading commercial vehicle manufacturer

|since 2014-06
|*Senior Software Engineer and Product Owner*
a|link:https://www.itsonix.eu/[@IT Sonix custom development GmbH]

* Software development and product ownership for custom software solutions in the automotive industry.
** Old Eclipse RCP application...
** Services and microservices...
** API development...

...for vehicle configuration and order management

* DevSecOps and security engineering for custom software solutions in the automotive industry.

|
|*Team Lead Product Management*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH] DevSecOps Project

* Leading a team of 4 product owners in varying customer and industry segments to deliver a comprehensive DevSecOps product suite.

|2012-06 to 2014-05
|*Senior Software Engineer*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH]

* Software development for custom software solutions in the automotive industry.

|2011-10 to 2012-05
|*Software Engineer*
a|link:https://itsonix.eu/[@IT Sonix custom development GmbH]

* Software development for custom software solutions in the automotive industry.

|2010-04 to 2011-09
|*Software Engineer*
a|link:https://www.heise.de/news/Software-AG-uebernimmt-restliche-Anteile-von-itCampus-1012299.html[@itcampus]

* Software development for custom software solutions in the automotive industry.

|===

////
**ronnypolley/ronnypolley** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 👯 I'm looking to collaborate on ...
- 🤔 I'm looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
////

